"""Central enums. StrEnum — persist the string *value*, never the ordinal."""

from __future__ import annotations

from enum import StrEnum


class Watcher(StrEnum):
    FED_WATCHER = "FED_WATCHER"
    KRW_WATCHER = "KRW_WATCHER"
    KOSPI_WATCHER = "KOSPI_WATCHER"
    US_WATCHER = "US_WATCHER"


class SignalDirection(StrEnum):
    UP = "UP"
    DOWN = "DOWN"
    FLAT = "FLAT"
    NEUTRAL = "NEUTRAL"


class MoveUnit(StrEnum):
    BPS = "BPS"
    KRW = "KRW"
    PCT = "PCT"
    INDEX_PCT = "INDEX_PCT"
    INDEX_POINTS = "INDEX_POINTS"
    SCORE = "SCORE"  # unitless composite (e.g. US pulse score −100..100)


class Horizon(StrEnum):
    NOWCAST = "NOWCAST"
    INTRADAY = "INTRADAY"
    W1 = "1W"
    D5 = "D5"
    D20 = "D20"
    M1 = "1M"
    D60 = "D60"
    M3 = "3M"
    M6 = "6M"
    M12 = "12M"
    Y3 = "3Y"
    Y10 = "10Y"


class ComparisonOperator(StrEnum):
    LT = "LT"
    LTE = "LTE"
    GT = "GT"
    GTE = "GTE"
    EQ = "EQ"
    NE = "NE"


class Regime(StrEnum):
    """Unified high-level macro regimes (Market Regime Engine output)."""

    GOLDILOCKS = "GOLDILOCKS"
    HAWKISH_GROWTH = "HAWKISH_GROWTH"
    HAWKISH_SLOWDOWN = "HAWKISH_SLOWDOWN"
    REINFLATION = "REINFLATION"
    STAGFLATION = "STAGFLATION"
    RECESSION_RISK = "RECESSION_RISK"
    LIQUIDITY_STRESS = "LIQUIDITY_STRESS"
    POLICY_EASING_TRANSITION = "POLICY_EASING_TRANSITION"
    USD_STRENGTH = "USD_STRENGTH"
    KRW_STRENGTH = "KRW_STRENGTH"
    KOREA_DECOUPLING = "KOREA_DECOUPLING"
    US_TECH_LEADERSHIP = "US_TECH_LEADERSHIP"
    VALUE_ROTATION = "VALUE_ROTATION"
    DEFENSIVE_ROTATION = "DEFENSIVE_ROTATION"
    REGIME_UNCERTAIN = "REGIME_UNCERTAIN"


REGIME_LABEL_KO: dict[Regime, str] = {
    Regime.GOLDILOCKS: "안정적 성장(저물가 호황)",
    Regime.HAWKISH_GROWTH: "긴축 속 성장",
    Regime.HAWKISH_SLOWDOWN: "긴축 속 경기 둔화",
    Regime.REINFLATION: "물가 재상승",
    Regime.STAGFLATION: "물가 오르며 경기 둔화",
    Regime.RECESSION_RISK: "경기침체 위험",
    Regime.LIQUIDITY_STRESS: "돈맥경화(유동성 경색)",
    Regime.POLICY_EASING_TRANSITION: "금리 인하 전환",
    Regime.USD_STRENGTH: "달러 강세(원화 약세)",
    Regime.KRW_STRENGTH: "원화 강세",
    Regime.KOREA_DECOUPLING: "한국 따로 가기(디커플링)",
    Regime.US_TECH_LEADERSHIP: "미국 기술주 주도",
    Regime.VALUE_ROTATION: "가치주로 이동",
    Regime.DEFENSIVE_ROTATION: "방어주로 이동",
    Regime.REGIME_UNCERTAIN: "방향 불확실",
}


def regime_ko(regime: Regime) -> str:
    return REGIME_LABEL_KO.get(regime, regime.value)


class AppMode(StrEnum):
    READ_ONLY = "READ_ONLY"
    PAPER = "PAPER"
    SHADOW = "SHADOW"
    APPROVAL = "APPROVAL"
    BOUNDED_LIVE = "BOUNDED_LIVE"
    FULL_AUTOMATION = "FULL_AUTOMATION"


class Book(StrEnum):
    STRATEGIC_REGIME = "STRATEGIC_REGIME"
    TACTICAL_ALPHA = "TACTICAL_ALPHA"
    HEDGE = "HEDGE"


class AssetClass(StrEnum):
    """The cross-asset universe for the MARKET WATCHER allocation view."""

    USD = "USD"  # 달러 (USD cash / dollar exposure)
    US_TREASURY = "US_TREASURY"  # 미국채
    US_EQUITY = "US_EQUITY"  # 미장
    KOREA_EQUITY = "KOREA_EQUITY"  # 국장
    CASH = "CASH"  # 현금 (KRW)
    BITCOIN = "BITCOIN"  # 비트코인
    GOLD = "GOLD"  # 금


ASSET_LABEL_KO: dict[AssetClass, str] = {
    AssetClass.USD: "달러(USD)",
    AssetClass.US_TREASURY: "미국채",
    AssetClass.US_EQUITY: "미국 주식",
    AssetClass.KOREA_EQUITY: "한국 주식",
    AssetClass.CASH: "원화 현금",  # KRW cash — 환노출 없는 방어 버퍼 (달러 자산과 구분)
    AssetClass.BITCOIN: "비트코인",
    AssetClass.GOLD: "금",
}


class ExposureDirection(StrEnum):
    INCREASE = "INCREASE"
    REDUCE = "REDUCE"
    FLAT = "FLAT"


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


class OrderState(StrEnum):
    TRADE_INTENT_CREATED = "TRADE_INTENT_CREATED"
    RISK_REVIEW_PENDING = "RISK_REVIEW_PENDING"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_APPROVED = "RISK_APPROVED"
    ORDER_SUBMISSION_PENDING = "ORDER_SUBMISSION_PENDING"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    BROKER_ACKNOWLEDGED = "BROKER_ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    AMENDMENT_PENDING = "AMENDMENT_PENDING"
    AMENDED = "AMENDED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELLED = "CANCELLED"
    REJECTED_BY_BROKER = "REJECTED_BY_BROKER"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    RECONCILIATION_ERROR = "RECONCILIATION_ERROR"


class RiskDecisionStatus(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    APPROVED_WITH_REDUCED_SIZE = "APPROVED_WITH_REDUCED_SIZE"
    MANUAL_APPROVAL_REQUIRED = "MANUAL_APPROVAL_REQUIRED"


class RiskCheckCode(StrEnum):
    # account-level
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    WEEKLY_LOSS_LIMIT = "WEEKLY_LOSS_LIMIT"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    MAX_GROSS_EXPOSURE = "MAX_GROSS_EXPOSURE"
    MAX_NET_EQUITY_EXPOSURE = "MAX_NET_EQUITY_EXPOSURE"
    MAX_USD_EXPOSURE = "MAX_USD_EXPOSURE"
    MIN_CASH_RATIO = "MIN_CASH_RATIO"
    BOOK_CAPITAL_LIMIT = "BOOK_CAPITAL_LIMIT"
    MAX_TURNOVER = "MAX_TURNOVER"
    MAX_CONCURRENT_POSITIONS = "MAX_CONCURRENT_POSITIONS"
    MAX_UNFILLED_EXPOSURE = "MAX_UNFILLED_EXPOSURE"
    DAILY_TRADE_COUNT = "DAILY_TRADE_COUNT"
    # position-level
    MAX_SINGLE_INSTRUMENT_WEIGHT = "MAX_SINGLE_INSTRUMENT_WEIGHT"
    MAX_SECTOR_WEIGHT = "MAX_SECTOR_WEIGHT"
    MAX_THEMATIC_OVERLAP = "MAX_THEMATIC_OVERLAP"
    MAX_FOREIGN_EQUITY_ETF = "MAX_FOREIGN_EQUITY_ETF"
    MAX_DURATION = "MAX_DURATION"
    MAX_INVERSE_EXPOSURE = "MAX_INVERSE_EXPOSURE"
    MAX_LEVERAGED_EXPOSURE = "MAX_LEVERAGED_EXPOSURE"
    MAX_CORRELATION_CLUSTER = "MAX_CORRELATION_CLUSTER"
    # order-level
    MAX_ORDER_NOTIONAL = "MAX_ORDER_NOTIONAL"
    MAX_ORDER_QUANTITY = "MAX_ORDER_QUANTITY"
    MAX_PCT_OF_ADV = "MAX_PCT_OF_ADV"
    MAX_SPREAD = "MAX_SPREAD"
    MAX_NAV_PREMIUM_DISCOUNT = "MAX_NAV_PREMIUM_DISCOUNT"
    MAX_SLIPPAGE = "MAX_SLIPPAGE"
    MIN_LIQUIDITY = "MIN_LIQUIDITY"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    STALE_SIGNAL = "STALE_SIGNAL"
    MARKET_HOURS = "MARKET_HOURS"
    INSTRUMENT_ALLOWED = "INSTRUMENT_ALLOWED"
    INSTRUMENT_ACTIVE = "INSTRUMENT_ACTIVE"
    STRATEGY_ALLOWED = "STRATEGY_ALLOWED"
    ORDER_TYPE_ALLOWED = "ORDER_TYPE_ALLOWED"
    PRICE_DEVIATION = "PRICE_DEVIATION"
    PENDING_ORDER_CONFLICT = "PENDING_ORDER_CONFLICT"
    # system-health
    KIWOOM_AUTH_HEALTH = "KIWOOM_AUTH_HEALTH"
    REST_HEALTH = "REST_HEALTH"
    WEBSOCKET_HEALTH = "WEBSOCKET_HEALTH"
    REALTIME_DATA_FRESHNESS = "REALTIME_DATA_FRESHNESS"
    WATCHER_DATA_FRESHNESS = "WATCHER_DATA_FRESHNESS"
    DB_HEALTH = "DB_HEALTH"
    CLOCK_SYNC = "CLOCK_SYNC"
    POSITION_RECONCILIATION = "POSITION_RECONCILIATION"
    PENDING_ORDER_RECONCILIATION = "PENDING_ORDER_RECONCILIATION"
    DUPLICATE_PROCESS = "DUPLICATE_PROCESS"
    KILL_SWITCH = "KILL_SWITCH"
